language: c
script: ./travis-tool.sh run_tests
before_script:
- sudo apt-get update -qq
- sudo apt-get install -y gdal-bin libgdal-dev libgdal1-dev netcdf-bin libproj-dev libgdal1h
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- ./travis-tool.sh bootstrap
- ./travis-tool.sh install_r rgeos
- ./travis-tool.sh install_r maptools
- ./travis-tool.sh install_deps
